{% set name = "linkcheckmd" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/linkcheckmd-{{ version }}.tar.gz
  sha256: 3a539c9a4e11697fc7fcc269d379accf93c8cccbf971f3cea0bae40912d9f609

build:
  entry_points:
    - linkcheckMarkdown = linkcheckmd.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.7
    - aiohttp >=3.3

test:
  imports:
    - linkcheckmd
  commands:
    - pip check
    - linkcheckMarkdown --help
  requires:
    - pip

about:
  home: https://github.com/scivision/linkchecker-markdown
  summary: Check links for Markdown-based site
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - julian-belina
